version: "3.7"
services:
  nexus3:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - cicdnet
  jenkins:
    image: jenkins:2.60.3
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - cicdnet
volumes:
  nexus-data:
  jenkins-data:

networks:
  cicdnet: